name: Ahmia Crawler Daily Job

on:
  schedule:
    - cron: '0 3 * * *'   # runs daily at 03:00 AM UTC
  workflow_dispatch:       # keeps the manual trigger option

jobs:
  crawl:
    runs-on: ubuntu-latest
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run crawler script
        run: python ahmia_crawler.py

