name: Ahmia Crawler Daily Job

on:
  schedule:
    - cron: '0 0 * * *' # runs every day at 00:00 UTC
  workflow_dispatch:     # allows you to manually trigger from Actions tab

jobs:
  run-crawler:
    runs-on: ubuntu-latest
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Ahmia crawler
        run: python ahmia_crawler.py
